import { JobsType } from "../JobTypes";

export const BandFJobs: JobsType[] = [
  {
    id: 1,
    LifeStyle: "Burgers & Fries LTD",
    name: "Trainee",
    isLocked: false,
    level: 1,
    maxLevel: 0,
    currentExperience: 0,
    currentSalary: 0,
    experienceToNextLevel: 180,
    baseSalary: 1,
    levelSalaryMultiplier: 1.05,
    levelExperienceMultiplier: 1.03,
  },
  {
    id: 2,
    LifeStyle: "Burgers & Fries LTD",
    name: "Cashier",
    isLocked: false,
    level: 1,
    maxLevel: 0,
    currentExperience: 0,
    currentSalary: 0,
    experienceToNextLevel: 80,
    baseSalary: 1.4,
    levelSalaryMultiplier: 1.07,
    levelExperienceMultiplier: 1.07,
  },
  {
    id: 3,
    LifeStyle: "Burgers & Fries LTD",
    name: "Burger Flipper",
    isLocked: false,
    level: 1,
    maxLevel: 0,
    currentExperience: 0,
    currentSalary: 0,
    experienceToNextLevel: 100,
    baseSalary: 1.4,
    levelSalaryMultiplier: 1.07,
    levelExperienceMultiplier: 1.07,
  },
  {
    id: 4,
    LifeStyle: "Burgers & Fries LTD",
    name: "Cook",
    isLocked: false,
    level: 1,
    maxLevel: 0,
    currentExperience: 0,
    currentSalary: 0,
    experienceToNextLevel: 120,
    baseSalary: 1.4,
    levelSalaryMultiplier: 1.07,
    levelExperienceMultiplier: 1.07,
  },
  {
    id: 5,
    LifeStyle: "Burgers & Fries LTD",
    name: "Shift Manager",
    isLocked: false,
    level: 1,
    maxLevel: 0,
    currentExperience: 0,
    currentSalary: 0,
    experienceToNextLevel: 140,
    baseSalary: 1.4,
    levelSalaryMultiplier: 1.07,
    levelExperienceMultiplier: 1.07,
  },
  {
    id: 6,
    LifeStyle: "Burgers & Fries LTD",
    name: "Store Manager",
    isLocked: false,
    level: 1,
    maxLevel: 0,
    currentExperience: 0,
    currentSalary: 0,
    experienceToNextLevel: 160,
    baseSalary: 1.4,
    levelSalaryMultiplier: 1.07,
    levelExperienceMultiplier: 1.07,
  },
  {
    id: 7,
    LifeStyle: "Burgers & Fries LTD",
    name: "Region Manager",
    isLocked: false,
    level: 1,
    maxLevel: 0,
    currentExperience: 0,
    currentSalary: 0,
    experienceToNextLevel: 180,
    baseSalary: 1.4,
    levelSalaryMultiplier: 1.07,
    levelExperienceMultiplier: 1.07,
  },
  {
    id: 8,
    LifeStyle: "Burgers & Fries LTD",
    name: "C.O.O",
    isLocked: false,
    level: 1,
    maxLevel: 0,
    currentExperience: 0,
    currentSalary: 0,
    experienceToNextLevel: 200,
    baseSalary: 1.4,
    levelSalaryMultiplier: 1.07,
    levelExperienceMultiplier: 1.07,
  },
  {
    id: 9,
    LifeStyle: "Burgers & Fries LTD",
    name: "C.E.O",
    isLocked: false,
    level: 1,
    maxLevel: 0,
    currentExperience: 0,
    currentSalary: 0,
    experienceToNextLevel: 220,
    baseSalary: 1.4,
    levelSalaryMultiplier: 1.07,
    levelExperienceMultiplier: 1.07,
  },
] as const;
